### ISSUE TITLE
Compile errors due to error in typings

### ISSUE THREAD

**Issue by greaterking** [LokiJS-Forge/LokiDB#157]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/LokiJS-Forge/LokiDB/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

<code><pre>
ERROR in node_modules/@lokidb/indexed-storage/types/loki/src/result_set.d.ts(220,36): error TS1005: ';' expected.
[ng] node_modules/@lokidb/indexed-storage/types/loki/src/result_set.d.ts(220,75): error TS1005: ';' expected.
[ng] node_modules/@lokidb/indexed-storage/types/loki/src/result_set.d.ts(220,119): error TS1005: ';' expected.
[ng] node_modules/@lokidb/indexed-storage/types/loki/src/result_set.d.ts(220,142): error TS1005: ':' expected.
[ng] node_modules/@lokidb/indexed-storage/types/loki/src/result_set.d.ts(220,153): error TS1005: ')' expected.
[ng] node_modules/@lokidb/indexed-storage/types/loki/src/result_set.d.ts(220,154): error TS1005: ';' expected.
[ng] node_modules/@lokidb/indexed-storage/types/loki/src/result_set.d.ts(220,158): error TS1005: ';' expected.
[ng] node_modules/@lokidb/loki/types/loki/src/result_set.d.ts(220,36): error TS1005: ';' expected.
[ng] node_modules/@lokidb/loki/types/loki/src/result_set.d.ts(220,75): error TS1005: ';' expected.
[ng] node_modules/@lokidb/loki/types/loki/src/result_set.d.ts(220,119): error TS1005: ';' expected.
[ng] node_modules/@lokidb/loki/types/loki/src/result_set.d.ts(220,142): error TS1005: ':' expected.
[ng] node_modules/@lokidb/loki/types/loki/src/result_set.d.ts(220,153): error TS1005: ')' expected.
[ng] node_modules/@lokidb/loki/types/loki/src/result_set.d.ts(220,154): error TS1005: ';' expected.
[ng] node_modules/@lokidb/loki/types/loki/src/result_set.d.ts(220,158): error TS1005: ';' expected.
</code></pre>

## Expected behavior

no errors and should be able to easily compile

## Minimal reproduction of the problem with instructions

No matter what I do I keep getting the same errors. I've it seems to stem from result_set.d.ts whose types are present in all 4 adapaters and loki itself.

## Environment

<pre><code>
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   ios-sim : 5.0.6
   NodeJS  : v8.11.3 (/usr/local/bin/node)
   npm     : 5.6.0
   OS      : macOS High Sierra
   Xcode   : Xcode 10.0 Build version 10L213o

</code></pre>

**Comment by greaterking** [comment]
Typescript 2.7.2

**Comment by Viatorus** [comment]
We are using Typescript 2.8.3 which supports conditional types. Your TS version does not support this/know this construct.

**Comment by greaterking** [comment]
`[ng] Date: 2018-10-17T16:08:20.182Z
[ng] Hash: bc7a6e4b8e25141e70f5
[ng] Time: 2769ms
[ng] chunk {main} main.js, main.js.map (main) 1.93 kB [initial] [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 681 bytes [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 38.7 kB [initial] [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 326 kB [initial] [rendered]
[ng] ERROR in **The Angular Compiler requires TypeScript >=2.7.2** and <2.8.0 but 2.8.4 was found instead.
[ng] ℹ ｢wdm｣: Failed to compile.
`

I tried to update..which worked ...but in ionic4(beta) as of the comment the angular compiler actually requires the lower version. Noting here in case some user experiencing the same issue and to note that its not loki's fault :D

**Comment by greaterking** [comment]
house keeping:

I was finally able to update to 2.9.2 and all the type errors have all but disappeared.
