### ISSUE TITLE
What is the best way to update the local database when syncing with server?

### ISSUE THREAD

**Issue by damien-murphy** [LokiJS-Forge/LokiDB#162]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/LokiJS-Forge/LokiDB/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In order to update the LokiDB stored in IndexedDB with the data returned from the server you must delete entire collection and re-insert all the data.

## Desired behavior
Pass all server objects and insert/update/delete is handled by LokiDB

## Minimal reproduction of the problem with instructions
Passing update server objects adds new entries

## What is the motivation / use case for changing the behavior?
Make it easier to sync large amounts of data

## Environment

<pre><code>
LokiDB version: 2.0.0-beta.8

Browser/Node version: Chrome 71
</code></pre>

**Comment by Viatorus** [comment]
Check out some issues at https://github.com/techfort/LokiJS
This topic is mention there already.
