### ISSUE TITLE
Support querying nested properties

### ISSUE THREAD

**Issue by stefanprobst** [LokiJS-Forge/LokiDB#164]
Querying nested properties with the dot-notation does not seem to work currently, since `Resultset.find()` [treats `property` as a simple Object key](https://github.com/LokiJS-Forge/LokiDB/blob/78994174c3626ddf6e3bbd92feb35a2727c7bc11/packages/loki/src/result_set.ts#L640). Has this changed compared to LokiJS?

**Comment by Viatorus** [comment]
Yes.
You have to register your nested property when creating a collection:

options.nestedProperties Array<Array<String>>

See some tests how it is used. The benefit over dot-notation is, it now
works everywhere.

**Comment by stefanprobst** [comment]
Thanks!

**Comment by stefanprobst** [comment]
That works. But how to register new nested properties on an existing collection?

**Comment by Viatorus** [comment]
This is not possible at the moment (like all other collection options). The implementation would be mostly cloning the collection to be sure all things are considered (btree index, unique index, fts,...)
