### ISSUE TITLE
Fuzzy search not behaving as expected in all cases?

### ISSUE THREAD

**Issue by gotenxds** [LokiJS-Forge/LokiDB#177]
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x?] Bug report  
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/LokiJS-Forge/LokiDB/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Hi, I have some issues with fuzzy search, I'm not sure if I'm just using incorrectly as I couldn't find anything about it in the docs
Fuzzy search works great, some of the time I'l give some examples that work and some that don't

with the following data set `['Tanglefoot', 'Shield', 'Acid Splash', 'Prestidigitation]`

The search term 'ash' should return `Acid Splash` but returns 'Shield'
The search term 'foot' should return 'Tanglefoot' but return 0 results
The search term 'digitation' should return 'Prestidigitation' but return 0 results 

How I use the fuzzy search:

```{ $fts: { query: { type: 'fuzzy', field: 'name', value: search.value, extended: true, prefix_length: 0 } } }```

**Comment by Viatorus** [comment]
Fuzzy uses leventhstein distance (max. distance is 2). All returned results look good to me.

I recommend the use of multiple FTS queries and weight them differently. So try to combine fuzzy and wildcards.

**Comment by gotenxds** [comment]
hi @Viatorus , thx for the quick answer, I was thinking I'm most likely doing something wrong, it's interesting I did not know you can combine the fts queries, I didn't really see a possibility for that in the types, can you give a quick syntax example of how to use multiple queries at once?

**Comment by Viatorus** [comment]
Checkout the documentation of [elastic search](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html) and the [test_cases](https://github.com/LokiJS-Forge/LokiDB/blob/master/packages/full-text-search/spec/node/QUERIES.ts). The query is very similar.

Untested:
```javascript
{
$fts: {
  query {
      type: "bool",
      should: [
        {
          type: "wildcard",
          field: "name",
          value: "*" + search.value,
          boost: 2
        },
        {
          type: "fuzzy",
          field: "name",
          value: search.value,
          extended: true,
          prefix_length: 0
        }
      ],
      minimum_should_match: 1
    },
  }
}
}
```
