### ISSUE TITLE
[bug] Searching on indexed collection causes error

### ISSUE THREAD

**Issue by UBy** [LokiJS-Forge/LokiDB#182]
## I'm submitting a...
`[x] Bug report`

## Current behavior

Using `findOne` on indexed collections (using default 'js' comparator) results in error:

`TypeError: this.comparator is not a function
    at AvlTreeIndex.locate (<path>/node_modules/@lokidb/loki/webpack:/@lokidb/loki/packages/loki/src/avl_index.ts:849:20)`

I thought that the 'js' comparator was default, so I would assume this to work out-of-the -box. Meaning I do not have to add anything to `comparatorMap`.

Collections without indexes don't have this problem.

So, either it's a bug, or I'm doing it wrong. But that is difficult to know due to the lack of documentation in this project.

## Expected behavior
Creating a collection with an index should be searchable

## Minimal reproduction of the problem with instructions

Create and search a collection like this:

```
FSStorage.register()
const db = new Loki('<path>/data`)
db.initializePersistence({ adapter: new FSStorage(), autosave: true, autoload: true })

interface Person {
    name: string
    email: string
}

const coll = db.addCollection<Person>('person', {
    rangedIndexes: {
           name: { indexTypeName: 'avl', comparatorName: 'js' }
     }
})

coll.insertOne({ name: 'Herbert', email: 'mail@com' })
coll.findOne({ name: 'Herbert' })
```

**Comment by Viatorus** [comment]
Hello,

I tried your example above and it works without any exception. Are you sure your code is correct?

**Comment by UBy** [comment]
Well obviously, if the code works for you, it is correct :)
The question is then, what is different for me?

I have to revisit my code, to see if it is somehow different of the example I posted.

**Comment by UBy** [comment]
Confirmed. There is no issue.
Seems something went wrong with the node modules.
After pulling them again, everything was fine.

**Comment by greaterking** [comment]
@UBy I seem to be having issue with this now somehow...do you remember how you fixed?

**Comment by UBy** [comment]
Not sure. Removed my database files and reinstalled node modules, and suddenly it was working. I can't say if any of those action made it work.
