### ISSUE TITLE
How is LokiDB the official successor of LokiJS?

### ISSUE THREAD

**Issue by beruic** [LokiJS-Forge/LokiDB#190]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/LokiJS-Forge/LokiDB/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
https://github.com/LokiJS-Forge/LokiDB claims that 

> LokiDB is the official successor of LokiJS.

, but I cannot find any reference stating this at LokiJS.

## Expected behavior
If it was really so, I'd expect LokiJS to make an official reference to LokiDB.

**Comment by xkem** [comment]
^^^^^^^

**Comment by lustremedia** [comment]
As it looks, lokiDB is a typescript port of lokiJS ... maybe that is a natural progression?

**Comment by beruic** [comment]
@lustremedia I'm putting an emphasis on the word **"official"** here. The point is that nothing in the legacy seems to validate this as an **official** successor.

**Comment by lustremedia** [comment]
@beruic yeah sure, my "natural progression" was more or less a shrug ¯\_(ツ)_/¯ comment ... I forget about emotions online sometimes

**Comment by Viatorus** [comment]
The owner of LokiJS (techfort) is the same owner as this group of LokiDB.

**Comment by beruic** [comment]
@Viatorus I thought about this, but @techfort is not listed under https://github.com/orgs/LokiJS-Forge/people, so I still fail to see this relation. Is it under another username? :)

Nevertheless, I started this issue because I was wondering. I still don't see any evidence of your claim being true @Viatorus, but I guess that as a member of the group, your statement at least hold some weight to it.

**Comment by Viatorus** [comment]
There also exist private member. ;)

And I think this would clear any uncertainty:
https://github.com/techfort/LokiJS/issues/525#issuecomment-272933595

Nevertheless, I think if someone wants to use and modernize LokiJS/DB, this
repository is a good starting point. I tried my best converting it to
TypeScript and improving it. I am proud of the full text search feature or
the fast lookup tree from obeliskos.
But I don't really use LokiDB (web technology in general) very much. If any
want to continue, please let me know. :)

**Comment by beruic** [comment]
I guess it's a wrap then :)

**Comment by elmarti** [comment]
I've made a few suggestions, but they may detract from the original functionality a little too much, so it may be a case of forking

**Comment by elmarti** [comment]
I'm a few weeks away from a proper release, but I've built similar database with a Mongo API here:
https://github.com/elmarti/camadb/tree/develop

For me this resolves the tickets I opened on this project:
- https://github.com/LokiJS-Forge/LokiDB/issues/193
- https://github.com/LokiJS-Forge/LokiDB/issues/194

It currently does not have indexing, but i'm seeing comparable speeds

**Comment by Bessonov** [comment]
@elmarti great! I'm looking for a fast, persistent and typescript based db solution. But I like a reactive approach. I can see only two projects for that requirement:
- [WatermelonDB](https://github.com/Nozbe/WatermelonDB). It's still used on an older project. Overall great and fast, but strange ideas around primary keys (you have very little control over them) and around synchronization makes it unusable for me.
- [RxDB](https://rxdb.info/). This is the current solution, but I'm not happy about the weight (there is some work was done in 10th version) and some flakiness on initialization/destroying. But I think it's more related to many abstractions rxdb -> pouchdb -> indexeddb. With last architectural changes we have possibility to drop pouchdb, but not implemented yet.

One thing you may keep in mind is the possibility to migrate the existing schema and data.

**Comment by elmarti** [comment]
Subscriptions/observables/update streaming is definitely in my periphery, but no concrete ideas as of yet, but here are some of the things i'll be adding in the coming weeks for the sake of the project i'm working on:

- Synchronisation adapter interface - ability to connect to synchronize with any service like MongoDB realm   (I want to add some kind of transaction support, this is not supported by Realm)
- Collection streaming - the internals already support this, just needs exposure via an API/researching the ideal way to expose this e.g callbacks, observables, async iterator etc
- Exposure of persistence interface - ability to provide a custom implementation for serialization
- UI composer - ability to bind UI components to the data - not a lot of ideas about this yet

If you have a specific request feel free to open a ticket on the repo or PR, I don't want to keep poking the Loki community 😄
