### ISSUE TITLE
Renaming LokiJS2?

### ISSUE THREAD

**Issue by Viatorus** [LokiJS-Forge/LokiDB#86]
What do you think about renaming LokiJS2 to a different name before releasing it?

Problem:
It is not easy to distinguish (using a search engine) between LokiJS and LokiJS2.
I know this problem from AngularJS and Angular 2...

I don't think this would dramatically decrease the popularity of this library. 

@obeliskos  @techfort 
What is your opinion?

I am open for proposals for a Nordic name. ;)

**Comment by techfort** [comment]
Hey! Sigyn is Loki's wife and Nari and Narfi are Loki's sons. Do they sound good?

**Comment by obeliskos** [comment]
At one time (several years ago) when we were brainstorming a version 2 of loki we attributed a codename of Skrymir which is another name for [Utgarda-Loki](https://en.wikipedia.org/wiki/Útgarða-Loki) or 'Loki of the Outyards'.  If you are interested, I think [techfort still has the repo](https://github.com/techfort/skrymir) were we used issues to discuss.

Perhaps [Flyting](http://thenorsegods.com/lokis-flyting/) or some theme related to binding which typescript might suggest.

@techfort I am almost ashamed to admit this but have you seen Almighty Johnsons?  Definately not cannon but mildy amusing and Loki appears 'Muspelheim in the house' :)

**Comment by Viatorus** [comment]
I didn't know about the previous LokiJS 2 (skrymir) repository. There are some interesting discussions - I would like to see something similar here. ;)

So as I can see, you would support renaming LokiJS 2. Thank you!

Currently, We have the following names :
* Sigyn
* Nari
* Narfi
* Skrymir
* Flyting

**Comment by Viatorus** [comment]
I thinking of appending a database related word to project name. So it would be easier to know what a library does just by the name: e.g. MongoDB, CouchDB, MySQL, SQLite...

Maybe `LokiDB` would be good enough?

**Comment by techfort** [comment]
LokiDB sounds good

**Comment by Viatorus** [comment]
Done. :)
